name: The Surrendering Life
favicon: null
layout_spectrum: 0.08305582357570529
typography_spectrum: 0.5863106660544872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07876499509438872
  lightness: 0.03481472097337246
  saturation: 0.5612010944169015
  rhythmicContrast: 0.2246002631727606
purpose: []
